---
- name: 3.5.2.3
  tags:
    - 3.5.2.3
    - level_1_server
    - level_1_workstation
  when:
    # section_3_5_2_3
    - iptables_outbound | bool
    - 'ansible_os_family != "Suse"'
  block:
    - name: |
        ---
        3.5.2.3 Ensure IPv4 outbound and established connections are configured
        > Allow new and established outbound connections
        ---
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: "{{ proto }}"
        match: state
        ctstate:
          - NEW
          - ESTABLISHED
        jump: ACCEPT
        ip_version: ipv4
      loop:
        - tcp
        - udp
        - icmp
      loop_control:
        loop_var: proto

    - name: |
        ---
        3.5.2.3 Ensure IPv4 outbound and established connections are configured
        > Allow established inbound connections
        ---
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ proto }}"
        match: state
        ctstate:
          - ESTABLISHED
        jump: ACCEPT
        ip_version: ipv4
      loop:
        - tcp
        - udp
        - icmp
      loop_control:
        loop_var: proto

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: "3.5.2.3"
      ansible.builtin.import_tasks:
        file: error_logging.yml
