---
bootstrap_pkgs:
  - iproute2
  - iputils-ping
  - kmod
  - cron
  - procps
  - iptables
  - auditd
  - ssh

login_defs: /etc/login.defs

grub_prefix: grub

list_repo: apt-cache policy
list_gpg_keys: apt-key list

aide_init_cmd: aideinit

valid_mandatory_access_controls:
  selinux:
    - libselinux1
  apparmor:
    - apparmor
    - apparmor-utils

apparmor_enforce: aa-enforce

ntp_systemd: ntp
chrony_systemd: chrony

chrony_systemd_service_file: "/lib/systemd/system/{{ chrony_systemd }}.service"

chrony_conf: "/etc/chrony/chrony.conf"

xorg_pkgs: "xserver-xorg*"

tcp_wrappers_pkg: "tcpd"

iptables_data: "/etc/iptables/rules.v4"
ip6tables_data: "/etc/iptables/rules.v6"

iptables_persist_pkg: "iptables-persistent"
iptables_persist_service: "netfilter-persistent"

auditd_pkgs:
  - auditd
  - audispd-plugins

cron_daemon: cron

sshd_pkg: "ssh"

pwquality_pkg: "libpam-pwquality"

pam_password_file: "/etc/pam.d/common-password"
pam_auth_file: "/etc/pam.d/common-auth"
