---
bootstrap_pkgs:
  - iproute
  - iputils
  - kmod
  - cronie
  - procps-ng
  - grubby
  - epel-release
  - iptables
  - audit
  - openssh-server

grub_prefix: grub2

list_repo: dnf repolist
list_gpg_keys: >
  rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n'

aide_init_cmd: aide --init

valid_mandatory_access_controls:
  selinux:
    - libselinux
    - policycoreutils

chrony_systemd: chronyd
chrony_systemd_service_file: >-
  /usr/lib/systemd/system/{{ chrony_systemd }}.service

chrony_conf: "/etc/chrony.conf"

xorg_pkgs: "xorg-x11*"

tcp_wrappers_pkg: "tcp_wrappers"

iptables_data: "/etc/sysconfig/iptables"
ip6tables_data: "/etc/sysconfig/ip6tables"

iptables_persist_pkg: "iptables-services"
iptables_persist_service: "iptables"

auditd_pkgs:
  - audit
  - audit-libs

cron_daemon: crond

sshd_pkg: "openssh-server"

pwquality_pkg: "libpwquality"

pam_password_file: "/etc/pam.d/system-auth"
