---
bootstrap_pkgs:
  - kmod
  - cronie
  - procps-ng
  - grubby

grub_prefix: grub2

list_repo: dnf repolist
list_gpg_keys: >
  rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n'

aide_init_cmd: aide --init

valid_mandatory_access_controls:
  selinux:
    - libselinux
    - policycoreutils
