---
bootstrap_pkgs:
  - iproute
  - iputils
  - kmod
  - cronie
  - procps
  - grubby
  - audit

grub_prefix: grub2

list_repo: zypper repos
list_gpg_keys: zypper repos

aide_init_cmd: aide --init

valid_mandatory_access_controls:
  selinux:
    - libselinux1
    - policycoreutils
  apparmor:
    - apparmor-parser
    - apparmor-utils

apparmor_enforce: enforce

ntp_systemd: ntpd
chrony_systemd: chronyd
chrony_systemd_service_file: >-
  /usr/lib/systemd/system/{{ chrony_systemd }}.service

chrony_conf: "/etc/chrony.conf"

xorg_pkgs: "xorg-x11*"

tcp_wrappers_pkg: "tcpd"

auditd_pkgs:
  - audit
  - audit-libs
