---
bootstrap_pkgs:
  - iproute
  - iputils
  - kmod
  - cronie
  - procps
  - grubby
  - audit
  - openssh-server

login_defs: /etc/login.defs

grub_prefix: grub2

list_repo: zypper repos
list_gpg_keys: zypper repos

aide_init_cmd: aide --init -B "database_out=file:/var/lib/aide/aide.db"
aide_bin: aide

valid_mandatory_access_controls:
  selinux:
    - libselinux1
    - policycoreutils
  apparmor:
    - apparmor-parser
    - apparmor-utils

apparmor_enforce: enforce

ntp_systemd: ntpd
chrony_systemd: chronyd
chrony_systemd_service_file: >-
  /usr/lib/systemd/system/{{ chrony_systemd }}.service

chrony_conf: "/etc/chrony.conf"

xorg_pkgs: "xorg-x11*"

tcp_wrappers_pkg: "tcpd"

auditd_pkgs:
  - audit
  - audit-libs

cron_daemon: cron

sshd_pkg: "openssh-server"

pwquality_pkg: "pam_pwquality"

pam_password_file: "/etc/pam.d/common-password"
pam_auth_file: "/etc/pam.d/common-auth"

verify_pkgs: "rpm -Va --nomtime --nosize --nomd5 --nolinkto"
