---
- name: 2.2.1.1 Ensure time synchronization is in use
  tags:
    - 2.2.1.1
    - level_1_server
    - level_1_workstation
  ansible.builtin.import_tasks:
    file: ./2.2.1.1.yml

- name: 2.2.1.2 Ensure ntp is configured
  tags:
    - 2.2.1.2
    - level_1_server
    - level_1_workstation
  ansible.builtin.import_tasks:
    file: ./2.2.1.2.yml

- name: 2.2.1.3 Ensure chrony is configured
  tags:
    - 2.2.1.3
    - level_1_server
    - level_1_workstation
  ansible.builtin.import_tasks:
    file: ./2.2.1.3.yml

- name: 2.2.1.4 Ensure systemd-timesyncd is configured
  tags:
    - 2.2.1.4
    - level_1_server
    - level_1_workstation
  ansible.builtin.import_tasks:
    file: ./2.2.1.4.yml
