---
- name: 4.2.2.2
  tags:
    - 4.2.2.2
    - level_1_server
    - level_1_workstation
  when:
    # section_4_2_2_2
    - journald_compress_files | bool
  block:
    - name: |
        ---
        4.2.2.2 Ensure journald is configured to compress large log files
        > Edit /etc/systemd/journald.conf
        ---
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^Compress\s*=\s*(?:(?!\byes\b).)*'
        line: "Compress=yes"
        state: present

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 4.2.2.2
      ansible.builtin.import_tasks:
        file: error_logging.yml
