---
- name: 4.2.2.3
  tags:
    - 4.2.2.3
    - level_1_server
    - level_1_workstation
  when:
    # section_4_2_2_3
    - journald_persistent_storage | bool
  block:
    - name: |
        ---
        4.2.2.2 Ensure journald is configured to write logfiles to persistent
        disk
        > Edit /etc/systemd/journald.conf
        ---
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^Storage\s*=\s*(?:(?!\bpersistent\b).)*'
        line: "Storage=persistent"
        state: present

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 4.2.2.3
      ansible.builtin.import_tasks:
        file: error_logging.yml
