---
- name: 4.2.2.1
  tags:
    - 4.2.2.1
    - level_1_server
    - level_1_workstation
  when:
    # section_4_2_2_1
    - journald_forward_to_syslog | bool
  block:
    - name: |
        ---
        4.2.2.1 Ensure journald is configured to send logs to rsyslog
        > Edit /etc/systemd/journald.conf
        ---
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^ForwardToSyslog\s*=\s*(?:(?!\byes\b).)*'
        line: "ForwardToSyslog=yes"
        state: present

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 4.2.2.1
      ansible.builtin.import_tasks:
        file: error_logging.yml
