---
- name: 4.2.2.1 Ensure journald is configured to send logs to rsyslog
  ansible.builtin.import_tasks:
    file: ./4.2.2.1.yml

- name: 4.2.2.2 Ensure journald is configured to compress large log files
  ansible.builtin.import_tasks:
    file: ./4.2.2.2.yml

- name: |
    4.2.2.3 Ensure journald is configured to write logfiles to persistent
    disk
  ansible.builtin.import_tasks:
    file: ./4.2.2.3.yml
