---
- name: 1.1 Filesystem Configuration
  tags:
    - 1.1.x
  ansible.builtin.import_tasks:
    file: ./1.1/main.yml

- name: 1.2 Configure Software Updates
  tags:
    - 1.2.x
  ansible.builtin.import_tasks:
    file: ./1.2/main.yml

- name: 1.3 Filesystem Integrity Checking
  tags:
    - 1.3.x
  ansible.builtin.import_tasks:
    file: ./1.3/main.yml
