---
- name: 1.4.2
  tags:
    - 1.4.2
    - level_1_server
    - level_1_workstation
  when:
    # section_1_4_2
    - bootloader_auth | bool
    - grub_v2
  block:
    - name: |
        ---
        1.4.2 Ensure bootloader password is set
        > Check if bootloader password is provided
        ---
      ansible.builtin.assert:
        that:
          - bootloader_password
        msg: "Please provide a bootloader password"

    - name: |
        ---
        1.4.2 Ensure bootloader password is set
        > Check if a password has been set (non RedHat)
        ---
      ansible.builtin.command: >-
        grep "password_pbkdf2\s+.+\s+grub\.pbkdf2\.sha512"
        {{ boot_loader_conf }}
      register: grep_out
      changed_when: false
      failed_when: grep_out.rc > 2
      when:
        - ansible_os_family != 'RedHat'

    - name: |
        ---
        1.4.2 Ensure bootloader password is set
        > Check if a password has been set (RedHat)
        ---
      ansible.builtin.command: >-
        grep "^GRUB2_PASSWORD=" {{ boot_loader_conf }}
      register: grep_out
      changed_when: false
      failed_when: grep_out.rc > 2
      when:
        - ansible_os_family == 'RedHat'

    - name: |
        ---
        1.4.2 Ensure bootloader password is set
        > Generate PBKDF2 password
        ---
      ansible.builtin.expect:
        command: "{{ grub_prefix }}-mkpasswd-pbkdf2"
        responses:
          "Enter password:": "{{ bootloader_password }}"
          "Reenter password": "{{ bootloader_password }}"
      register: pbkdf2_out
      changed_when: false

    - name: |
        ---
        1.4.2 Ensure bootloader password is set
        > Edit /etc/grub.d/99_ansible_bootloader_password
        ---
      vars:
        bootloader_pw_hash: >-
          {{ pbkdf2_out.stdout_lines[-1].split(" ")[-1] }}
      ansible.builtin.template:
        src: etc/grub.d/99_ansible_bootloader_password.j2
        dest: /etc/grub.d/99_ansible_bootloader_password
        mode: "0755"
        owner: root
        group: root
      notify: "grub mkconfig"
      when:
        - ansible_os_family != 'RedHat'

    - name: |
        ---
        1.4.2 Ensure bootloader password is set
        > Edit /boot/grub2/user.cfg
        ---
      vars:
        bootloader_pw_hash: >-
          {{ pbkdf2_out.stdout_lines[-1].split(" ")[-1] }}
      ansible.builtin.lineinfile:
        path: /boot/grub2/user.cfg
        regexp: "^GRUB2_PASSWORD=.*"
        line: "GRUB2_PASSWORD={{ bootloader_pw_hash }}"
        mode: "0600"
        owner: root
        group: root
        create: true
      notify: "grub mkconfig"
      when:
        - ansible_os_family == 'RedHat'

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 1.4.2
      ansible.builtin.import_tasks:
        file: error_logging.yml
