---
- name: 1.4.1
  tags:
    - 1.4.1
    - level_1_server
    - level_1_workstation
  when:
    # section_1_4_1
    - bootloader_conf_perm | bool
  block:
    - name: |
        ---
        1.4.1 Ensure permissions on bootloader config are configured
        > Change permissions on {{ boot_loader_conf }}
        ---
      when:
        - grub_v2
      ansible.builtin.file:
        path: "{{ boot_loader_conf }}"
        state: file
        owner: root
        group: root
        mode: g-rwx,o-rwx

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 1.4.1
      ansible.builtin.import_tasks:
        file: error_logging.yml
