---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: "Include d0ublew.cis_independent_linux"
      tags:
        - always
      ansible.builtin.include_role:
        name: "d0ublew.cis_independent_linux"
