---
- name: 1.5.4
  tags:
    - 1.5.4
  when:
    - section_1_5_4
  block:
    - name: |
        ---
        1.5.4 Ensure prelink is disabled
        > Check if prelink is installed
        ---
      vars:
        prelink_match: >
          {{ ansible_facts.packages | dict2items |
             selectattr('key', 'match', '^prelink') | length }}
      when:
        - prelink_match | int > 0
      block:
        - name: |
            ---
            1.5.4 Ensure prelink is disabled
            > Restore binaries to normal if prelink is installed
            ---
          ansible.builtin.command: "prelink -ua"
          changed_when: false

        - name: |
            ---
            1.5.4 Ensure prelink is disabled
            > Uninstall prelink
            ---
          ansible.builtin.package:
            name: prelink
            state: absent

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 1.5.4
      ansible.builtin.import_tasks:
        file: error_logging.yml
