---
- name: 1.5.2
  tags:
    - 1.5.2
    - level_1_server
    - level_1_workstation
  when:
    # section_1_5_2
    - enable_nx | bool
    - not is_container
  block:
    - name: |
        ---
        1.5.2 Ensure XD/NX support is enabled
        > Check if NX is active
        ---
      ansible.builtin.shell: >
        dmesg | grep '\sNX\s.*\sprotection:\s' | grep -q active
      register: nx_out
      changed_when: false
      failed_when: false

    - name: |
        ---
        1.5.2 Ensure XD/NX support is enabled
        > Add boot parameter 'noexec=on' (RedHat|Suse)
        ---
      when:
        - nx_out.rc == 1
        - ansible_os_family == 'RedHat' or
          ansible_os_family == 'Suse'
      ansible.builtin.command: >
        grubby --update-kernel=ALL --args="noexec=on"
      notify: "reboot"

    - name: |
        ---
        1.5.2 Ensure XD/NX support is enabled
        > Add boot parameter 'noexec=on' (Debian)
        ---
      when:
        - nx_out.rc == 1
        - ansible_os_family == 'Debian'
        - grub_v2
      ansible.builtin.lineinfile:
        path: "/etc/default/grub"
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?:(?!noexec=on).)*)"'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 noexec=on"'
        backrefs: true
        backup: true
      notify: "grub mkconfig"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 1.5.2
      ansible.builtin.import_tasks:
        file: error_logging.yml
