---
- name: 1.5.3
  tags:
    - 1.5.3
  when:
    # section_1_5_3
    - enable_aslr | bool
  block:
    - name: |
        ---
        1.5.3 Ensure address space layout randomization (ASLR) is enabled
        > Edit /etc/sysctl.d/99-aslr.conf
        ---
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/99-aslr.conf
        regexp: '^kernel\.randomize_va_space\s*=\s*(?:(?!2).)*$'
        line: "kernel.randomize_va_space = 2"
        create: true
        mode: 0644
        state: present
      notify: "sysctl reload"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 1.5.3
      ansible.builtin.import_tasks:
        file: error_logging.yml
