---
- name: 1.1.1 Disable unused filesystems
  tags:
    - 1.1.1
  ansible.builtin.import_tasks:
    file: ./1.1.1/main.yml

- name: |
    1.1.2 Ensure /tmp is configured
    1.1.3 Ensure nodev option set on /tmp partition
    1.1.4 Ensure nosuid option set on /tmp partition
    1.1.5 Ensure noexec option set on /tmp partition
  vars:
    tmp_systemd: true
  ansible.builtin.import_tasks:
    file: ./1.1.2-5.yml

- name: |
    1.1.6 Ensure separate partition exists for /var
  ansible.builtin.import_tasks:
    file: ./1.1.6.yml

- name: |
    1.1.7 Ensure separate partition exists for /var/tmp
    1.1.8 Ensure nodev option set on /var/tmp partition
    1.1.9 Ensure nosuid option set on /var/tmp partition
    1.1.10 Ensure noexec option set on /var/tmp partition
  ansible.builtin.import_tasks:
    file: ./1.1.7-10.yml

- name: |
    1.1.11 Ensure separate partition exists for /var/log
  ansible.builtin.import_tasks:
    file: ./1.1.11.yml

- name: |
    1.1.12 Ensure separate partition exists for /var/log/audit
  ansible.builtin.import_tasks:
    file: ./1.1.12.yml

- name: |
    1.1.13 Ensure separate partition exists for /home
    1.1.14 Ensure nodev option set on /home partition
  ansible.builtin.import_tasks:
    file: ./1.1.13-14.yml

- name: |
    1.1.15 Ensure nodev option set on /dev/shm partition
    1.1.16 Ensure nosuid option set on /dev/shm partition
    1.1.17 Ensure noexec option set on /dev/shm partition
  ansible.builtin.import_tasks:
    file: ./1.1.15-17.yml

- name: |
    1.1.18 Ensure nodev option set on removable media partition
    1.1.19 Ensure nosuid option set on removable media partition
    1.1.20 Ensure noexec option set on removable media partition
  ansible.builtin.import_tasks:
    file: ./1.1.18-20.yml

- name: 1.1.21 Ensure sticky bit is set on all world-writable directories
  ansible.builtin.import_tasks:
    file: ./1.1.21.yml

- name: 1.1.22 Disable automounting
  ansible.builtin.import_tasks:
    file: ./1.1.22.yml

- name: 1.1.23 Disable USB Storage
  ansible.builtin.import_tasks:
    file: ./1.1.23.yml
