---
- name: 2.1.1
  tags:
    - 2.1.1
    - level_1_server
    - level_1_workstation
  when:
    - disable_inetd_service_chargen | bool
  vars:
    svc_name: chargen
  block:
    - name: |
        ---
        2.1.1 Ensure {{ svc_name }} services are not enabled
        > Get config file(s) with {{ svc_name }} service (xinetd)
        ---
      ansible.builtin.shell: >
        grep -lRP '^service\s+{{ svc_name }}\b'
        /etc/xinetd.d/* /etc/xinetd.conf
      register: matched_file
      changed_when: false
      failed_when: false

    - name: |
        ---
        2.1.1 Ensure {{ svc_name }} services are not enabled
        > Set `disable = yes` where necessary (xinetd)
        ---
      when:
        - matched_file.rc != 2
      vars:
        part_1_rg: '^service\s+{{ svc_name }}(?:{|\b[.\s]*?{)[^}]*?'
      ansible.builtin.replace:
        path: "{{ file }}"
        regexp: >-
          ({{ part_1_rg }})disable\s*=\s*no(\b)
        replace: '\1disable = yes\2'
      loop: "{{ matched_file.stdout_lines }}"
      loop_control:
        label: "{{ file }}"
        loop_var: file

    - name: |
        ---
        2.1.1 Ensure {{ svc_name }} services are not enabled
        > Get config file(s) with {{ svc_name }} service (inetd)
        ---
      ansible.builtin.shell: >
        grep -lRP '^{{ svc_name }}\b'
        /etc/inetd.d/* /etc/inetd.conf
      register: matched_file
      changed_when: false
      failed_when: false

    - name: |
        ---
        2.1.1 Ensure {{ svc_name }} services are not enabled
        > Comment out any lines starting with {{ svc_name }} (inetd)
        ---
      when:
        - matched_file.rc != 2
      ansible.builtin.replace:
        path: "{{ file }}"
        regexp: '^({{ svc_name }}\b.+)'
        replace: '# \1'
      loop: "{{ matched_file.stdout_lines }}"
      loop_control:
        label: "{{ file }}"
        loop_var: file

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 2.1.1
      ansible.builtin.import_tasks:
        file: error_logging.yml
