---
- name: 2.1.1-9 Ensure inetd services are not enabled
  tags:
    - 2.1.1-9
    - 2.1.1
    - 2.1.1_chargen
    - 2.1.2
    - 2.1.2_daytime
    - 2.1.3
    - 2.1.3_discard
    - 2.1.4
    - 2.1.4_echo
    - 2.1.5
    - 2.1.5_time
    - 2.1.6
    - 2.1.6_rsh
    - 2.1.6_shell
    - 2.1.6_rlogin
    - 2.1.6_login
    - 2.1.6_rexec
    - 2.1.6_exec
    - 2.1.7
    - 2.1.7_talk
    - 2.1.7_ntalk
    - 2.1.8
    - 2.1.8_telnet
    - 2.1.9
    - 2.1.9_tftp
  vars:
    inetd_services:
      - name:
          xinetd: chargen
          inetd: chargen
        desc: "2.1.1 Ensure chargen services are not enabled"
        section_id: 2.1.1

      - name:
          xinetd: daytime
          inetd: daytime
        desc: "2.1.2 Ensure daytime services are not enabled"
        section_id: 2.1.2

      - name:
          xinetd: discard
          inetd: chargen
        desc: "2.1.3 Ensure discard services are not enabled"
        section_id: 2.1.3

      - name:
          xinetd: echo
          inetd: echo
        desc: "2.1.4 Ensure echo services are not enabled"
        section_id: 2.1.4

      - name:
          xinetd: time
          inetd: time
        desc: "2.1.5 Ensure time services are not enabled"
        section_id: 2.1.5

      - name:
          xinetd: rsh
          inetd: shell
        desc: "2.1.6 Ensure rsh server is not enabled"
        section_id: 2.1.6

      - name:
          xinetd: rlogin
          inetd: login
        desc: "2.1.6 Ensure rsh server is not enabled"
        section_id: 2.1.6

      - name:
          xinetd: rexec
          inetd: exec
        desc: "2.1.6 Ensure rsh server is not enabled"
        section_id: 2.1.6

      - name:
          xinetd: talk
          inetd: talk
        desc: "2.1.7 Ensure talk server is not enabled"
        section_id: 2.1.7

      - name:
          xinetd: ntalk
          inetd: ntalk
        desc: "2.1.7 Ensure talk server is not enabled"
        section_id: 2.1.7

      - name:
          xinetd: telnet
          inetd: telnet
        desc: "2.1.8 Ensure telnet server is not enabled"
        section_id: 2.1.8

      - name:
          xinetd: tftp
          inetd: tftp
        desc: "2.1.9 Ensure tftp server is not enabled"
        section_id: 2.1.9

  ansible.builtin.include_tasks:
    file: ./2.1.x.yml
    apply:
      tags:
        - 2.1.1-9
        - "{{ svc.section_id }}"
        - "{{ svc.section_id }}_{{ svc.name.xinetd }}"
        - "{{ svc.section_id }}_{{ svc.name.inetd }}"
  loop: "{{ inetd_services }}"
  loop_control:
    loop_var: svc
    label: "{{ svc.desc }}"
  when:
    - svc.name not in disable_inetd_services.keys() or
      (disable_inetd_services[svc.name] | bool)

- name: 2.1.10 Ensure xinetd is not enabled
  ansible.builtin.import_tasks:
    file: ./2.1.10.yml
