---
- name: 1.3.2
  tags:
    - level_1_server
    - level_1_workstation
    - 1.3.2
  when:
    # section_1_3_2
    - aide_cronjob | bool
  block:
    - name: |
        ---
        1.3.2 Ensure filesystem integrity is regularly checked
        > Create a cron job
        ---
      ansible.builtin.cron:
        name: "AIDE filesystem integrity check"
        user: "{{ aide_cron_user }}"
        weekday: "{{ aide_cron_weekday }}"
        month: "{{ aide_cron_month }}"
        day: "{{ aide_cron_day }}"
        hour: "{{ aide_cron_hour }}"
        minute: "{{ aide_cron_minute }}"
        job: "$(command -v {{ aide_bin }}) --check"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 1.3.2
      ansible.builtin.import_tasks:
        file: error_logging.yml
