---
##########
#
# 1.1
#
##########

# 1.1.1
disable_cramfs: "{{ section_1_1_1_1 }}"
disable_freevxfs: "{{ section_1_1_1_2 }}"
disable_jffs2: "{{ section_1_1_1_3 }}"
disable_hfs: "{{ section_1_1_1_4 }}"
disable_hfsplus: "{{ section_1_1_1_5 }}"
disable_squashfs: "{{ section_1_1_1_6 }}"
disable_udf: "{{ section_1_1_1_7 }}"
limit_vfat: "{{ section_1_1_1_8 }}"

# 1.1.2-5
tmp_nodev: "{{ section_1_1_3 }}"
tmp_nosuid: "{{ section_1_1_4 }}"
tmp_noexec: "{{ section_1_1_5 }}"

# 1.1.7-10
var_tmp_nodev: "{{ section_1_1_8 }}"
var_tmp_nosuid: "{{ section_1_1_9 }}"
var_tmp_noexec: "{{ section_1_1_10 }}"

# 1.1.13-14
home_nodev: "{{ section_1_1_14 }}"

# 1.1.15-17
dev_shm_nodev: "{{ section_1_1_15 }}"
dev_shm_nosuid: "{{ section_1_1_16 }}"
dev_shm_noexec: "{{ section_1_1_17 }}"

# 1.1.22
disable_autofs: "{{ section_1_1_22 }}"

# 1.1.23
disable_usb_storage_fs: "{{ section_1_1_23 }}"

##########
#
# 1.2
#
##########

# 1.2.1
audit_repos: "{{ section_1_2_1 }}"

# 1.2.2
audit_gpg: "{{ section_1_2_2 }}"

##########
#
# 1.3
#
##########

# 1.3.1
install_aide: "{{ section_1_3_1 }}"

# 1.3.2
aide_cronjob: "{{ section_1_3_2 }}"
aide_cron_user: root
aide_cron_weekday: "*"
aide_cron_month: "*"
aide_cron_day: "*"
aide_cron_hour: "1"
aide_cron_minute: "*"

##########
#
# 1.4
#
##########

# 1.4.1
bootloader_conf_perm: "{{ section_1_4_1 }}"

# 1.4.2
bootloader_auth: "{{ section_1_4_2 }}"
bootloader_superuser: "root"
bootloader_password: ""

# 1.4.3
system_auth: "{{ section_1_4_3 }}"
root_password: ""

# 1.4.4
disable_interactive_boot: "{{ section_1_4_4 }}"
etc_sysconfig_boot: /etc/sysconfig/boot

##########
#
# 1.5
#
##########

# 1.5.1
restrict_coredump: "{{ section_1_5_1 }}"

# 1.5.2
enable_nx: "{{ section_1_5_2 }}"

# 1.5.3
enable_aslr: "{{ section_1_5_3 }}"

# 1.5.4
disable_prelink: "{{ section_1_5_4 }}"

##########
#
# 1.6
#
##########

mandatory_access_control:
  Debian: apparmor
  Suse: selinux
  RedHat: selinux

# 1.6.1.1
install_mandatory_access_control: "{{ section_1_6_1_1 }}"

# 1.6.2.1
configure_bootloader_selinux: "{{ section_1_6_2_1 }}"

# 1.6.2.2
enforce_selinux_state: "{{ section_1_6_2_2 }}"

# 1.6.2.3
enable_selinux_policy: "{{ section_1_6_2_3 }}"
selinuxtype: targeted

# 1.6.2.4
uninstall_setroubleshoot: "{{ section_1_6_2_4 }}"

# 1.6.2.5
uninstall_mcstrans: "{{ section_1_6_2_5 }}"

# 1.6.2.6
audit_unconfined_daemons: "{{ section_1_6_2_6 }}"

# 1.6.3.1
configure_bootloader_apparmor: "{{ section_1_6_3_1 }}"

# 1.6.3.2
enforce_apparmor: "{{ section_1_6_3_2 }}"

##########
#
# 1.7
#
##########

# 1.7.1.1
audit_motd: "{{ section_1_7_1_1 }}"
etc_motd: "Hello"

# 1.7.1.2
audit_etc_issue: "{{ section_1_7_1_2 }}"

# 1.7.1.3
audit_etc_issue_net: "{{ section_1_7_1_3 }}"

# 1.7.1.4
etc_motd_perms: "{{ section_1_7_1_4 }}"

# 1.7.1.5
etc_issue_perms: "{{ section_1_7_1_5 }}"

# 1.7.1.6
etc_issue_net_perms: "{{ section_1_7_1_6 }}"

# 1.7.2
gdm_login_banner: "{{ section_1_7_2 }}"
gdm_banner_message: >-
  Authorized uses only. All activity may be monitored and reported.

##########
#
# 1.8
#
##########

update_all_packages: "{{ section_1_8 }}"
