---
##########
#
# 2.1
#
##########

# 2.1.1-9
disable_inetd_services:
  chargen: "{{ section_2_1_1 }}"
  daytime: "{{ section_2_1_2 }}"
  discard: "{{ section_2_1_3 }}"
  echo: "{{ section_2_1_4 }}"
  time: "{{ section_2_1_5 }}"
  rsh: "{{ section_2_1_6_rsh }}"
  rlogin: "{{ section_2_1_6_rlogin }}"
  rexec: "{{ section_2_1_6_rexec }}"
  talk: "{{ section_2_1_7_talk }}"
  ntalk: "{{ section_2_1_7_ntalk }}"
  telnet: "{{ section_2_1_8 }}"
  tftp: "{{ section_2_1_9 }}"

# 2.1.10
disable_xinetd_systemd: "{{ section_2_1_10 }}"
disable_xinetd_update_rc_d: "{{ section_2_1_10 }}"

##########
#
# 2.2
#
##########

# 2.2.1.1
configure_time_synchronization: "{{ section_2_2_1_1 }}"

# ntp, chrony, systemd-timesyncd
# NOTE:
# AlmaLinux does not have both ntp and systemd-timesyncd
# systemd-timesyncd does not work in container
time_synchronization: systemd-timesyncd

# 2.2.1.2
configure_ntp: "{{ section_2_2_1_2 }}"

time_sync_remote_server: time1.google.com

ntp_options:
  - kod
  - nomodify
  - notrap
  - nopeer
  - noquery

# 2.2.1.3
configure_chrony: "{{ section_2_2_1_3 }}"

# 2.2.1.4
configure_systemd_timesyncd: "{{ section_2_2_1_4 }}"

systemd_timesyncd:
  main_ntp:
    - time1.google.com
    - time2.google.com
  fallback_ntp:
    - time3.google.com
    - time4.google.com
  root_distance_max: 1
