---
##########
#
# 2.1
#
##########

# 2.1.1-9
disable_inetd_services:
  chargen: "{{ section_2_1_1 }}"
  daytime: "{{ section_2_1_2 }}"
  discard: "{{ section_2_1_3 }}"
  echo: "{{ section_2_1_4 }}"
  time: "{{ section_2_1_5 }}"
  rsh: "{{ section_2_1_6_rsh }}"
  rlogin: "{{ section_2_1_6_rlogin }}"
  rexec: "{{ section_2_1_6_rexec }}"
  talk: "{{ section_2_1_7_talk }}"
  ntalk: "{{ section_2_1_7_ntalk }}"
  telnet: "{{ section_2_1_8 }}"
  tftp: "{{ section_2_1_9 }}"

# 2.1.10
disable_xinetd_systemd: "{{ section_2_1_10 }}"
disable_xinetd_update_rc_d: "{{ section_2_1_10 }}"

##########
#
# 2.2
#
##########

# 2.2.1.1
configure_time_synchronization: "{{ section_2_2_1_1 }}"

# ntp, chrony, systemd-timesyncd
# NOTE:
# AlmaLinux does not have both ntp and systemd-timesyncd
# systemd-timesyncd does not work in container
time_synchronization: systemd-timesyncd

# 2.2.1.2
configure_ntp: "{{ section_2_2_1_2 }}"

time_sync_remote_server: time1.google.com

ntp_options:
  - kod
  - nomodify
  - notrap
  - nopeer
  - noquery

# 2.2.1.3
configure_chrony: "{{ section_2_2_1_3 }}"

# 2.2.1.4
configure_systemd_timesyncd: "{{ section_2_2_1_4 }}"

systemd_timesyncd:
  main_ntp:
    - time1.google.com
    - time2.google.com
  fallback_ntp:
    - time3.google.com
    - time4.google.com
  root_distance_max: 1

# 2.2.2
uninstall_x_window_system: "{{ section_2_2_2 }}"

# 2.2.3-14,16-17
disable_special_purpose_services:
  avahi-daemon: "{{ section_2_2_3 }}"
  cups: "{{ section_2_2_4 }}"
  dhcpd: "{{ section_2_2_5 }}"
  slapd: "{{ section_2_2_6 }}"
  nfs: "{{ section_2_2_7_nfs }}"
  rpcbind: "{{ section_2_2_7_rpcbind }}"
  named: "{{ section_2_2_8 }}"
  vsfptd: "{{ section_2_2_9 }}"
  httpd: "{{ section_2_2_10_httpd }}"
  nginx: "{{ section_2_2_10_nginx }}"
  apache: "{{ section_2_2_10_apache }}"
  apache2: "{{ section_2_2_10_apache2 }}"
  lighttpd: "{{ section_2_2_10_lighttpd }}"
  dovecot: "{{ section_2_2_11_dovecot }}"
  courier-imap: "{{ section_2_2_11_courier_imap }}"
  cyrus-imap: "{{ section_2_2_11_cyrus_imap }}"
  smb: "{{ section_2_2_12_smb }}"
  samba: "{{ section_2_2_12_samba }}"
  squid: "{{ section_2_2_13 }}"
  snmpd: "{{ section_2_2_14 }}"
  rsyncd: "{{ section_2_2_16 }}"
  ypserv: "{{ section_2_2_17_ypserv }}"
  nis: "{{ section_2_2_17_nis }}"

# 2.2.15
local_only_mta: "{{ section_2_2_15 }}"
