---
##########
#
# 4.1
#
##########

# 4.1.1.1
conf_audit_log_storage_size: "{{ section_4_1_1_1 }}"

# measured in MB (Megabytes)
max_log_file: 10

# 4.1.1.2
space_left_action: SYSLOG
halt_system_if_audit_logs_full: "{{ section_4_1_1_2 }}"

# 4.1.1.3
rotate_logs: "{{ section_4_1_1_3 }}"

# 4.1.2
install_auditd_pkgs: "{{ section_4_1_2 }}"

# 4.1.3
enable_auditd: "{{ section_4_1_3 }}"

# 4.1.4
audit_processes_before_auditd: "{{ section_4_1_3 }}"
