---
- name: 4.1.3
  tags:
    - 4.1.3
    - level_2_server
    - level_2_workstation
  when:
    # section_4_1_3
    - enable_auditd | bool
    - not is_container
  block:
    - name: |
        ---
        4.1.3 Ensure auditd service is enabled
        > Enable auditd via systemd
        ---
      when:
        - has_systemd
      ansible.builtin.systemd:
        name: auditd
        enabled: true

    - name: |
        ---
        4.1.3 Ensure auditd service is enabled
        > Enable auditd via update-rc.d
        ---
      when:
        - has_update_rc_d
      block:
        - name: |
            ---
            4.1.3 Ensure auditd service is enabled
            > Check if auditd is enabled
            ---
          ansible.builtin.shell: >
            ls /etc/rc*.d | grep xinetd | grep '^S.*'
          register: auditd_update_rc
          changed_when: false
          failed_when: false

        - name: |
            ---
            4.1.3 Ensure auditd service is enabled
            > Enable auditd via update-rc.d
            ---
          when:
            - auditd_update_rc.stdout_lines | length == 0
          ansible.builtin.shell: >
            update-rc.d auditd enable
          changed_when: true

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 4.1.3
      ansible.builtin.import_tasks:
        file: error_logging.yml
