---
- name: 4.1.14
  tags:
    - 4.1.14
    - level_2_server
    - level_2_workstation
  when:
    # section_4_1_14
    - audit_mounts | bool
  block:
    - name: |
        ---
        4.1.14 Ensure successful file system mounts are collected
        > Edit /etc/auditd/rules.d/90-mounts.rules
        ---
      ansible.builtin.template:
        src: >-
          etc/audit/rules.d/90-mounts.rules.{{ ansible_userspace_bits }}.j2
        dest: /etc/audit/rules.d/90-mounts.rules
        owner: root
        group: root
        mode: "0600"
      notify: "reload auditd"
      register: rules_out

    - name: |
        ---
        4.1.14 Ensure successful file system mounts are collected
        > Notify reboot handler
        ---
      when:
        - rules_out.changed
      ansible.builtin.debug:
        msg: Notify reboot handler
      notify: "reboot"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 4.1.14
      ansible.builtin.import_tasks:
        file: error_logging.yml
