---
- name: 4.1.9
  tags:
    - 4.1.9
    - level_2_server
    - level_2_workstation
  when:
    # section_4_1_9
    - audit_login | bool
  block:
    - name: |
        ---
        4.1.9 Ensure login and logout events are collected
        > Edit /etc/auditd/rules.d/90-logins.rules
        ---
      ansible.builtin.copy:
        src: etc/audit/rules.d/90-logins.rules
        dest: /etc/audit/rules.d/90-logins.rules
        owner: root
        group: root
        mode: "0600"
      notify: "reload auditd"
      register: rules_out

    - name: |
        ---
        4.1.9 Ensure login and logout events are collected
        > Notify reboot handler
        ---
      when:
        - rules_out.changed
      ansible.builtin.debug:
        msg: Notify reboot handler
      notify: "reboot"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 4.1.9
      ansible.builtin.import_tasks:
        file: error_logging.yml
