---
- name: 4.1.19
  tags:
    - 4.1.19
    - level_2_server
    - level_2_workstation
  when:
    # section_4_1_19
    - immutable_audit_conf | bool
  block:
    - name: |
        ---
        4.1.19 Ensure the audit configuration is immutable
        > Edit /etc/auditd/rules.d/99-finalize.rules
        ---
      ansible.builtin.copy:
        src: >-
          etc/audit/rules.d/99-finalize.rules
        dest: /etc/audit/rules.d/99-finalize.rules
        owner: root
        group: root
        mode: "0600"
      notify: "reload auditd"
      register: rules_out

    - name: |
        ---
        4.1.19 Ensure the audit configuration is immutable
        > Notify reboot handler
        ---
      when:
        - rules_out.changed
      ansible.builtin.debug:
        msg: Notify reboot handler
      notify: "reboot"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 4.1.19
      ansible.builtin.import_tasks:
        file: error_logging.yml
