---
- name: 4.1.1 Configure Data Retention
  tags:
    - 4.1.1
  ansible.builtin.import_tasks:
    file: ./4.1.1/main.yml

- name: 4.1.2 Ensure auditd is installed
  ansible.builtin.import_tasks:
    file: ./4.1.2.yml

- name: 4.1.3 Ensure auditd service is enabled
  ansible.builtin.import_tasks:
    file: ./4.1.3.yml

- name: 4.1.4 Ensure auditing for process that start prior to auditd is enabled
  ansible.builtin.import_tasks:
    file: ./4.1.4.yml
