---
- name: Init Provision
  become: true
  gather_facts: false
  hosts: all
  tasks:
    - name: Test ping
      ansible.builtin.raw: ping -c4 1.1.1.1
      register: ping_out
      changed_when: false
      failed_when: '"4 packets transmitted, 4 received, 0% packet loss" not in ping_out.stdout'
