---
- name: Compile rules
  ansible.builtin.shell: >
    augenrules --load
  register: augen
  failed_when:
    - "'There was an error in line' in augen.stderr"
  changed_when: false

- name: Restart auditd
  ansible.builtin.shell: >
    service auditd restart
  changed_when: false
