---
- name: Update grub2 configuration
  ansible.builtin.command: >
    {{ grub_prefix }}-mkconfig -o {{ boot_loader_conf }}
  changed_when: false

# - name: Set reboot flag
#   ansible.builtin.set_fact:
#     reboot: true
#   listen: "reboot"
