---
- name: Reload tmp.mount via systemd
  when: has_systemd
  ansible.builtin.systemd:
    name: tmp.mount
    masked: false
    enabled: true
    state: reloaded
    daemon_reload: true
  listen: "systemctl reload tmp.mount"

- name: Reload auditd
  ansible.builtin.include_tasks:
    file: auditd.yml
  listen: "reload auditd"

- name: Set reboot flag
  ansible.builtin.set_fact:
    reboot: true
  listen: "reboot"

- name: Reload systemd
  when: has_systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "systemd daemon-reload"

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  failed_when: false
  listen: "sysctl reload"

- name: Update grub2 configuration
  ansible.builtin.include_tasks:
    file: grub.yml
  listen: "grub mkconfig"

- name: Reload rsyslogd
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  listen: "reload rsyslogd"
