---
- name: Reload tmp.mount via systemd
  ansible.builtin.systemd:
    name: tmp.mount
    masked: false
    enabled: true
    state: reloaded
    daemon_reload: true
  listen: "systemctl reload tmp.mount"

- name: Set reboot flag
  ansible.builtin.set_fact:
    reboot: true
  listen: "reboot"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "systemd daemon-reload"

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  failed_when: false
  listen: "sysctl reload"
