---
- name: 6.1.14
  tags:
    - 6.1.14
    - level_1_server
    - level_1_workstation
  when:
    # section_6_1_14
    - audit_sgid_executables | bool
  block:
    - name: |
        ---
        6.1.14 Audit SGID executables
        > Get all SGID executables
        ---
      ansible.builtin.shell: >-
        df -P | awk '{if (NR!=1) print $6}' |
        xargs -I '{}' find '{}' -xdev  -type f -perm -2000
      register: sgid_exes

    - name: |
        ---
        6.1.14 Audit SGID executables
        > List all SGID executables
        ---
      ansible.builtin.debug:
        msg: "{{ sgid_exes.stdout_lines }}"

    - name: Info logging
      when:
        - sgid_exes.stdout_lines | length > 0
      vars:
        section_id: 6.1.14
        info_details: |-
          Please review found SGID executables
      ansible.builtin.import_tasks:
        file: info_logging.yml

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 6.1.14
      ansible.builtin.import_tasks:
        file: error_logging.yml
