---
- name: 6.1.11
  tags:
    - 6.1.11
    - level_1_server
    - level_1_workstation
  when:
    # section_6_1_11
    - no_unowned_files_or_dirs | bool
  block:
    - name: |
        ---
        6.1.11 Ensure no unowned files or directories exist
        > Create dummy user to own unowned files or directories
        ---
      when:
        - create_dummy_user
      ansible.builtin.user:
        name: "{{ dummy_username }}"
        shell: /bin/false
        create_home: true

    - name: |
        ---
        6.1.11 Ensure no unowned files or directories exist
        > Find unowned files or directories
        ---
      ansible.builtin.shell: >-
        df -P | awk '{if (NR!=1) print $6}' |
        xargs -I'{}' -n1 find '{}' -xdev -nouser
      register: unowned_files_or_dirs
      changed_when: false

    - name: |
        ---
        6.1.11 Ensure no unowned files or directories exist
        > Assign found unowned files or dirs to the user
        {{ unowned_default_user }}
        ---
      ansible.builtin.file:
        path: "{{ file }}"
        owner: "{{ unowned_default_user }}"
      loop: "{{ unowned_files_or_dirs.stdout_lines }}"
      loop_control:
        loop_var: file
        label: "{{ file }}"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 6.1.11
      ansible.builtin.import_tasks:
        file: error_logging.yml
