---
- name: 6.1.1 Audit system file permissions
  ansible.builtin.import_tasks:
    file: ./6.1.1.yml

- name: 6.1.2-9 Ensure permissions on critical files are configured
  tags:
    - 6.1.2-9
    - 6.1.2
    - 6.1.3
    - 6.1.4
    - 6.1.5
    - 6.1.6
    - 6.1.7
    - 6.1.8
    - 6.1.9
  vars:
    critical_files:
      - section_id: 6.1.2
        file_name: /etc/passwd
        owner: root
        group: root
        mode: "0644"

      - section_id: 6.1.3
        file_name: /etc/shadow
        owner: root
        group: root
        mode: "0640"

      - section_id: 6.1.4
        file_name: /etc/group
        owner: root
        group: root
        mode: "0644"

      - section_id: 6.1.5
        file_name: /etc/gshadow
        owner: root
        group: root
        mode: "0640"

      - section_id: 6.1.6
        file_name: "/etc/passwd-"
        owner: root
        group: root
        mode: "0600"

      - section_id: 6.1.7
        file_name: "/etc/shadow-"
        owner: root
        group: root
        mode: "0640"

      - section_id: 6.1.8
        file_name: "/etc/group-"
        owner: root
        group: root
        mode: "0644"

      - section_id: 6.1.9
        file_name: "/etc/gshadow-"
        owner: root
        group: root
        mode: "0640"

  ansible.builtin.include_tasks:
    file: ./6.1.2-9.yml
    apply:
      tags:
        - 6.1.2-9
        - "{{ file.section_id }}"
  loop: "{{ critical_files }}"
  loop_control:
    loop_var: file
    label: >-
      {{ file.section_id }} Ensure permissions on {{ file.file_name }} are
      configured
  when:
    - file.file_name not in critical_files_perms.keys() or
      (critical_files_perms[file.file_name]) | bool

- name: 6.1.10 Ensure no world writable files exist
  ansible.builtin.import_tasks:
    file: ./6.1.10.yml

- name: 6.1.11 Ensure no unowned files or directories exist
  ansible.builtin.import_tasks:
    file: ./6.1.11.yml

- name: 6.1.12 Ensure no ungrouped files or directories exist
  ansible.builtin.import_tasks:
    file: ./6.1.12.yml

- name: 6.1.13 Audit SUID executables
  ansible.builtin.import_tasks:
    file: ./6.1.13.yml

- name: 6.1.14 Audit SGID executables
  ansible.builtin.import_tasks:
    file: ./6.1.14.yml
