---
- name: 4.2.1.2
  tags:
    - 4.2.1.2
    - level_1_server
    - level_1_workstation
  when:
    # section_4_2_1_2
    - install_rsyslog | bool
  block:
    - name: |
        ---
        4.2.1.2 Ensure rsyslog Service is enabled
        > Enable rsyslog via systemd
        ---
      when:
        - has_systemd
      ansible.builtin.systemd:
        name: rsyslog
        enabled: true
        state: "started"

    - name: |
        ---
        4.2.1.2 Ensure rsyslog Service is enabled
        > Enable rsyslog via update-rc.d
        ---
      when:
        - has_update_rc_d
      block:
        - name: |
            ---
            4.2.1.2 Ensure rsyslog Service is enabled
            > Check if rsyslog is enabled
            ---
          ansible.builtin.shell: >-
            find /etc -wholename '/etc/rc?.d/S*rsyslog*' |
            awk -F '/' '{print $3}' |
            sort -u |
            grep -P '^rc[2-5]\.d$'
          register: rsyslog_rc_d
          changed_when: false
          failed_when: false

        - name: |
            ---
            4.2.1.2 Ensure rsyslog Service is enabled
            > Enable rsyslog via update-rc.d
            ---
          when:
            - rsyslog_rc_d.stdout_lines | length != 4
          ansible.builtin.command: >-
            update-rc.d rsyslog enable
          changed_when: true

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 4.2.1.2
      ansible.builtin.import_tasks:
        file: error_logging.yml
