---
- name: 4.2.1.3
  tags:
    - 4.2.1.3
    - level_1_server
    - level_1_workstation
  when:
    # section_4_2_1_3
    - rsyslog_rules_conf | bool
  block:
    - name: |
        ---
        4.2.1.3 Ensure logging is configured
        > Edit /etc/rsyslog.d/99-cis-rules.conf
        ---
      ansible.builtin.copy:
        src: etc/rsyslog.d/99-cis-rules.conf
        dest: /etc/rsyslog.d/99-cis-rules.conf
        owner: root
        group: root
        mode: "0644"
      notify: "reload rsyslogd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 4.2.1.3
      ansible.builtin.import_tasks:
        file: error_logging.yml
