---
- name: 4.2.1.1 Ensure rsyslog is installed
  ansible.builtin.import_tasks:
    file: ./4.2.1.1.yml

- name: 4.2.1.2 Ensure rsyslog Service is enabled
  ansible.builtin.import_tasks:
    file: ./4.2.1.2.yml

- name: 4.2.1.3 Ensure logging is configured
  ansible.builtin.import_tasks:
    file: ./4.2.1.3.yml

- name: 4.2.1.4 Ensure rsyslog default file permissions configured
  ansible.builtin.import_tasks:
    file: ./4.2.1.4.yml

- name: 4.2.1.5 Ensure rsyslog is configured to send logs to a remote host
  ansible.builtin.import_tasks:
    file: ./4.2.1.5.yml

- name: |
    4.2.1.6 Ensure remote rsyslog messages are only accepted on designated log
    hosts
  ansible.builtin.import_tasks:
    file: ./4.2.1.6.yml
