---
- name: 3.3.4
  tags:
    - 3.3.4
    - level_1_server
    - level_1_workstation
  when:
    # section_3_3_4
    - hosts_allow_perms | bool
  block:
    - name: |
        ---
        3.3.4 Ensure permissions on /etc/hosts.allow are configured
        > Set permissions to root:root 0644
        ---
      ansible.builtin.file:
        path: /etc/hosts.allow
        owner: root
        group: root
        mode: "0644"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 3.3.4
      ansible.builtin.import_tasks:
        file: error_logging.yml
