---
- name: 3.3.1
  tags:
    - 3.3.1
    - level_1_server
    - level_1_workstation
  when:
    # section_3_3_1
    - install_tcp_wrappers | bool
  block:
    - name: |
        ---
        3.3.1 Ensure TCP Wrappers is installed
        > Install {{ tcp_wrappers_pkg }} via package manager
        ---
      ansible.builtin.package:
        name: "{{ tcp_wrappers_pkg }}"
        state: present

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 3.3.1
      ansible.builtin.import_tasks:
        file: error_logging.yml
