---
- name: 4.2.3
  tags:
    - 4.2.3
    - level_1_server
    - level_1_workstation
  when:
    # section_4_2_3
    - logfiles_permissions | bool
  block:
    - name: |
        ---
        4.2.3 Ensure permissions on all logfiles are configured
        > chmod g-wx,o-rwx on all /var/log/ files
        ---
      ansible.builtin.command: >-
        find /var/log -type f -exec chmod g-wx,o-rwx "{}" + -o -type d -exec
        chmod g-w,o-rwx "{}" +
      changed_when: false

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 4.2.3
      ansible.builtin.import_tasks:
        file: error_logging.yml
