---
- name: 3.2.8
  tags:
    - 3.2.8
    - level_1_server
    - level_1_workstation
  when:
    # section_3_2_8
    - enable_tcp_syn_cookies | bool
  block:
    - name: |
        ---
        3.2.8 Ensure TCP SYN Cookies are enabled
        > Edit /etc/sysctl.d/99-tcp-syn-cookies.conf
        ---
      vars:
        confs:
          - key: net.ipv4.tcp_syncookies
            value: 1
        esc_key: "{{ conf.key | regex_escape() }}"
        esc_value: "{{ conf.value | regex_escape() }}"
        rg_template: >-
          ^{{ esc_key }}\s*=\s*(?:(?!\b{{ esc_value }}\b).)*$
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/99-tcp-syn-cookies.conf
        regexp: "{{ rg_template }}"
        line: "{{ conf.key }} = {{ conf.value }}"
        state: present
        create: true
        backup: true
        owner: root
        group: root
        mode: "0644"
      loop: "{{ confs }}"
      loop_control:
        loop_var: conf
        label: "{{ conf.key }} = {{ conf.value }}"
      notify: "sysctl reload"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 3.2.8
      ansible.builtin.import_tasks:
        file: error_logging.yml
