---
- name: 3.2.3
  tags:
    - 3.2.3
    - level_1_server
    - level_1_workstation
  when:
    # section_3_2_3
    - reject_secure_icmp_redirects | bool
  block:
    - name: |
        ---
        3.2.3 Ensure secure ICMP redirects are not accepted
        > Edit /etc/sysctl.d/99-secure-icmp-redirects.conf
        ---
      vars:
        confs:
          - key: net.ipv4.conf.all.secure_redirects
            value: 0
          - key: net.ipv4.conf.default.secure_redirects
            value: 0
        esc_key: "{{ conf.key | regex_escape() }}"
        esc_value: "{{ conf.value | regex_escape() }}"
        rg_template: >-
          ^{{ esc_key }}\s*=\s*(?:(?!\b{{ esc_value }}\b).)*$
      diff: true
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/99-secure-icmp-redirects.conf
        regexp: "{{ rg_template }}"
        line: "{{ conf.key }} = {{ conf.value }}"
        state: present
        create: true
        backup: true
        owner: root
        group: root
        mode: "0644"
      loop: "{{ confs }}"
      loop_control:
        loop_var: conf
        label: "{{ conf.key }} = {{ conf.value }}"
      notify: "sysctl reload"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 3.2.3
      ansible.builtin.import_tasks:
        file: error_logging.yml
