---
- name: 3.2.9
  tags:
    - 3.2.9
    - level_1_server
    - level_1_workstation
  when:
    # section_3_2_9
    - reject_ipv6_router_advertisements | bool
  block:
    - name: |
        ---
        3.2.9 Ensure IPv6 router advertisements are not accepted
        > Edit /etc/sysctl.d/99-ipv6-router-ad.conf
        ---
      vars:
        confs:
          - key: net.ipv6.conf.all.accept_ra
            value: 0
          - key: net.ipv6.conf.default.accept_ra
            value: 0
        esc_key: "{{ conf.key | regex_escape() }}"
        esc_value: "{{ conf.value | regex_escape() }}"
        rg_template: >-
          ^{{ esc_key }}\s*=\s*(?:(?!{{ esc_value }}).)*$
      diff: true
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/99-ipv6-router-ad.conf
        regexp: "{{ rg_template }}"
        line: "{{ conf.key }} = {{ conf.value }}"
        state: present
        create: true
        backup: true
        owner: root
        group: root
        mode: "0644"
      loop: "{{ confs }}"
      loop_control:
        loop_var: conf
        label: "{{ conf.key }} = {{ conf.value }}"
      notify: "sysctl reload"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 3.2.9
      ansible.builtin.import_tasks:
        file: error_logging.yml
