---
- name: 6.2.2
  tags:
    - 6.2.2
    - level_1_server
    - level_1_workstation
  when:
    # section_6_2_2
    - no_legacy_entries_etc_passwd | bool
  block:
    - name: |
        ---
        6.2.2 Ensure no legacy "+" entries exist in /etc/passwd
        > Remove any line with "+" on the first field
        ---
      ansible.builtin.lineinfile:
        path: /etc/passwd
        regexp: '^\+:'
        state: absent

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 6.2.2
      ansible.builtin.import_tasks:
        file: error_logging.yml
