---
- name: 6.2.8
  tags:
    - 6.2.8
    - level_1_server
    - level_1_workstation
  when:
    # section_6_2_8
    - user_home_dir_perms_conf | bool
  block:
    - name: |
        ---
        6.2.8 Ensure users' home directories permissions are 750 or more
        restrictive
        > Get users home directories from /etc/passwd
        ---
      ansible.builtin.shell: >-
        grep -E -v '^(halt|sync|shutdown)' /etc/passwd |
        awk -F: '($3>={{ uid_min }} && $7!="/bin/false" && $7!="/sbin/nologin"
        && $7!="/usr/sbin/nologin") { print $0 }'
      changed_when: false
      register: user_entries

    - name: |
        ---
        6.2.8 Ensure users' home directories permissions are 750 or more
        restrictive
        > Set permissions to {{ home_dir_perms }}
        ---
      vars:
        home_dir: "{{ user.strip().split(':')[5] }}"
      ansible.builtin.file:
        path: "{{ home_dir }}"
        mode: "{{ home_dir_perms }}"
      loop: "{{ user_entries.stdout_lines }}"
      loop_control:
        loop_var: user
        label: "{{ user }}"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 6.2.8
      ansible.builtin.import_tasks:
        file: error_logging.yml
