---
- name: 6.2.14
  tags:
    - 6.2.14
    - level_1_server
    - level_1_workstation
  when:
    # section_6_2_14
    - no_dot_rhosts_file | bool
  block:
    - name: |
        ---
        6.2.14 Ensure no users have .rhosts files
        > Get users home directories from /etc/passwd
        ---
      ansible.builtin.shell: >-
        grep -E -v '^(halt|sync|shutdown)' /etc/passwd |
        awk -F: '($3>={{ uid_min }} && $7!="/bin/false" && $7!="/sbin/nologin"
        && $7!="/usr/sbin/nologin") { print $6 }'
      changed_when: false
      register: user_home_dir

    - name: |
        ---
        6.2.14 Ensure no users have .rhosts files
        > Remove .rhosts file if exist
        ---
      ansible.builtin.file:
        path: "{{ file }}/.rhosts"
        state: absent
        follow: false
        recurse: false
      loop: "{{ user_home_dir.stdout_lines }}"
      loop_control:
        loop_var: file
        label: "{{ file }}/.rhosts"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 6.2.14
      ansible.builtin.import_tasks:
        file: error_logging.yml
