---
- name: 1.6.2.6
  when:
    # section_1_6_2_6
    - audit_unconfined_daemons | bool
    - mac == 'selinux'
  block:
    - name: |
        ---
        1.6.2.6 Ensure no unconfined daemons exist
        > Check for unconfined daemons
        ---
      ansible.builtin.shell: >
        ps -eZ | grep -Ee "initrc" -e "unconfined_service" |
        grep -Evw "tr|ps|grep|bash|awk" | tr ':' ' ' | awk '{print $NF}'
      changed_when: false
      failed_when: false
      register: unconfined_daemons

    - name: |
        ---
        1.6.2.6 Ensure no unconfined daemons exist
        > List unconfined daemons
        ---
      ansible.builtin.debug:
        msg: "{{ unconfined_daemons.stdout_lines }}"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 1.6.2.6
      ansible.builtin.import_tasks:
        file: error_logging.yml
