---
- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled
  tags:
    - 1.1.1.1
    - level_1_server
    - level_1_workstation
  ansible.builtin.import_tasks:
    file: ./1.1.1.1.yml

- name: 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled
  tags:
    - 1.1.1.2
    - level_1_server
    - level_1_workstation
  ansible.builtin.import_tasks:
    file: ./1.1.1.2.yml

- name: 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled
  tags:
    - 1.1.1.3
    - level_1_server
    - level_1_workstation
  ansible.builtin.import_tasks:
    file: ./1.1.1.3.yml

- name: 1.1.1.4 Ensure mounting of hfs filesystems is disabled
  tags:
    - 1.1.1.4
    - level_1_server
    - level_1_workstation
  ansible.builtin.import_tasks:
    file: ./1.1.1.4.yml

- name: 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled
  tags:
    - 1.1.1.5
    - level_1_server
    - level_1_workstation
  ansible.builtin.import_tasks:
    file: ./1.1.1.5.yml

- name: 1.1.1.6 Ensure mounting of squashfs filesystems is disabled
  tags:
    - 1.1.1.6
    - level_1_server
    - level_1_workstation
  ansible.builtin.import_tasks:
    file: ./1.1.1.6.yml

- name: 1.1.1.7 Ensure mounting of udf filesystems is disabled
  tags:
    - 1.1.1.7
    - level_1_server
    - level_1_workstation
  ansible.builtin.import_tasks:
    file: ./1.1.1.7.yml

- name: 1.1.1.8 Ensure mounting of FAT filesystems is limited
  tags:
    - 1.1.1.8
    - level_2_server
    - level_2_workstation
  ansible.builtin.import_tasks:
    file: ./1.1.1.8.yml
