---
- name: 3.1.2
  tags:
    - 3.1.2
    - level_1_server
    - level_1_workstation
  when:
    # section_3_1_2
    - disable_packet_redirect_sending | bool
  block:
    - name: |
        ---
        3.1.2 Ensure packet redirect sending is disabled
        > Edit /etc/sysctl.d/99-packet-redirect-sending.conf
        ---
      vars:
        confs:
          - key: net.ipv4.conf.all.send_redirects
            value: 0
          - key: net.ipv4.conf.default.send_redirects
            value: 0
        esc_key: "{{ conf.key | regex_escape() }}"
        esc_value: "{{ conf.value | regex_escape() }}"
        rg_template: >-
          ^{{ esc_key }}\s*=\s*(?:(?!\b{{ esc_value }}\b).)*$
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/99-packet-redirect-sending.conf
        regexp: "{{ rg_template }}"
        line: "{{ conf.key }} = {{ conf.value }}"
        state: present
        create: true
        backup: true
        owner: root
        group: root
        mode: "0644"
      loop: "{{ confs }}"
      loop_control:
        loop_var: conf
        label: "{{ conf.key }} = {{ conf.value }}"
      notify: "sysctl reload"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 3.1.2
      ansible.builtin.import_tasks:
        file: error_logging.yml
