---
- name: 4.1 Configure System Auditing (auditd)
  tags:
    - 4.1.x
  ansible.builtin.import_tasks:
    file: ./4.1/main.yml

- name: 4.2 Configure Logging
  tags:
    - 4.2.x
  ansible.builtin.import_tasks:
    file: ./4.2/main.yml

- name: 4.3 Ensure logrotate is configured
  ansible.builtin.import_tasks:
    file: ./4.3.yml
