---
- name: 1.1.11
  tags:
    - 1.1.11
  when:
    - section_1_1_11
  block:
    - name: |
        ---
        1.1.11 Ensure separate partition exists for /var/log
        ---
      vars:
        section_id: 1.1.11
        info_details: |-
          Ensure separate partition exists for /var/log
      ansible.builtin.import_tasks:
        file: info_logging.yml
      when: >
        '/var/log' not in (ansible_mounts | map(attribute='mount') | list)
