---
- name: Ensure kmod package is installed
  tags:
    - always
  ansible.builtin.package:
    name: kmod
    state: present

- name: 1.1.1 Disable unused filesystems
  tags:
    - 1.1.1
  ansible.builtin.import_tasks:
    file: ./1.1.1/main.yml

- name: |
    1.1.2 Ensure /tmp is configured
    1.1.3 Ensure nodev option set on /tmp partition
    1.1.4 Ensure nosuid option set on /tmp partition
    1.1.5 Ensure noexec option set on /tmp partition
  tags:
    - 1.1.2-5
  vars:
    tmp_systemd: true
  ansible.builtin.import_tasks:
    file: ./1.1.2-5.yml

- name: |
    1.1.6 Ensure separate partition exists for /var
  tags:
    - 1.1.6
  ansible.builtin.import_tasks:
    file: ./1.1.6.yml

# - name: |
#     1.1.7 Ensure separate partition exists for /var/tmp
#     1.1.8 Ensure nodev option set on /var/tmp partition
#     1.1.9 Ensure nosuid option set on /var/tmp partition
#     1.1.10 Ensure noexec option set on /var/tmp partition
#   tags:
#     - 1.1.7-10
#   ansible.builtin.import_tasks:
#     file: ./1.1.7-10.yml

- name: Caught errors summary
  tags:
    - always
  ansible.builtin.debug:
    msg: |
      Count: {{ error_count }}
      Affected: {{ error_list }}
