---
- name: 5.4.1.5
  tags:
    - 5.4.1.5
    - level_1_server
    - level_1_workstation
  when:
    # section_5_4_1_5
    - audit_last_pw_change | bool
  block:
    - name: |
        ---
        5.4.1.5 Ensure all users last password change date is in the past
        > Get users whose last password change date is in the future
        ---
      ansible.builtin.shell: >-
        for user in $(cut -d: -f1 /etc/shadow); do
        last=$(chage --list $user |
          grep '^Last password change' |
          cut -d: -f2 |
          xargs -I{} -n1 date -d {} +"%s");
        [[ $last -gt $(date +"%s") ]] && echo "$user:$last"; done
      args:
        executable: /bin/bash
      register: matched_users
      changed_when: false
      failed_when: matched_users.rc > 1

    - name: |
        ---
        5.4.1.5 Ensure all users last password change date is in the past
        > Expire the password of found users
        ---
      vars:
        username: "{{ user.strip().split(':')[0] }}"
      ansible.builtin.command: >-
        chage -E 0 {{ username }}
      loop: "{{ matched_users.stdout_lines }}"
      loop_control:
        loop_var: user
        label: "{{ user }}"
      changed_when: true

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.4.1.5
      ansible.builtin.import_tasks:
        file: error_logging.yml
