---
- name: 5.2.6
  tags:
    - 5.2.6
    - level_1_server
    - level_1_workstation
  when:
    # section_5_2_6
    - sshd_x11_forwarding | bool
  block:
    - name: |
        ---
        5.2.6 Ensure SSH X11 forwarding is disabled
        > Edit /etc/ssh/sshd_config
        ---
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^X11Forwarding\s+(?:(?!\bno\b).)*'
        line: "X11Forwarding no"
        create: true
        owner: root
        group: root
        mode: "0600"
      notify: "reload sshd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.2.6
      ansible.builtin.import_tasks:
        file: error_logging.yml
