---
- name: 5.2.10
  tags:
    - 5.2.10
    - level_1_server
    - level_1_workstation
  when:
    # section_5_2_10
    - sshd_disable_root_login | bool
  block:
    - name: |
        ---
        5.2.10 Ensure SSH root login is disabled
        > Edit /etc/ssh/sshd_config
        ---
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin\s+(?:(?!\bno\b).)*'
        line: "PermitRootLogin no"
        create: true
        owner: root
        group: root
        mode: "0600"
      notify: "reload sshd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.2.10
      ansible.builtin.import_tasks:
        file: error_logging.yml
