---
- name: 5.2.20
  tags:
    - 5.2.20
    - level_1_server
    - level_1_workstation
  when:
    # section_5_2_20
    - sshd_pam_conf | bool
    - ansible_os_family != 'RedHat'
  block:
    - name: |
        ---
        5.2.20 Ensure SSH PAM is enabled
        > Edit /etc/ssh/sshd_config
        ---
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^UsePAM\s+(?:(?!\byes\b).)*'
        line: "UsePAM yes"
        create: true
        owner: root
        group: root
        mode: "0600"
      notify: "reload sshd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.2.20
      ansible.builtin.import_tasks:
        file: error_logging.yml
