---
- name: 5.2.5
  tags:
    - 5.2.5
    - level_1_server
    - level_1_workstation
  when:
    # section_5_2_5
    - sshd_log_level_conf | bool
  block:
    - name: |
        ---
        5.2.5 Ensure SSH LogLevel is appropriate
        > Edit /etc/ssh/sshd_config
        ---
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^LogLevel\s+(?:(?!\b{{ sshd_log_level }}\b).)*'
        line: "LogLevel {{ sshd_log_level }}"
        create: true
        owner: root
        group: root
        mode: "0600"
      notify: "reload sshd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.2.5
      ansible.builtin.import_tasks:
        file: error_logging.yml
