---
- name: 5.2.19
  tags:
    - 5.2.19
    - level_1_server
    - level_1_workstation
  when:
    # section_5_2_19
    - sshd_banner_conf | bool
  block:
    - name: |
        ---
        5.2.19 Ensure SSH warning banner is configured
        > Edit /etc/ssh/sshd_config
        ---
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Banner\s+(?:(?!\b{{ sshd_banner | regex_escape }}\b).)*'
        line: "Banner {{ sshd_banner }}"
        create: true
        owner: root
        group: root
        mode: "0600"
      notify: "reload sshd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.2.19
      ansible.builtin.import_tasks:
        file: error_logging.yml
