---
- name: 5.2.22
  tags:
    - 5.2.22
    - level_1_server
    - level_1_workstation
  when:
    # section_5_2_22
    - sshd_max_startups_conf | bool
  block:
    - name: |
        ---
        5.2.22 Ensure SSH MaxStartups is configured
        > Edit /etc/ssh/sshd_config
        ---
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxStartups\s+(?:(?!\b{{ sshd_max_startups }}\b).)*'
        line: "MaxStartups {{ sshd_max_startups }}"
        create: true
        owner: root
        group: root
        mode: "0600"
      notify: "reload sshd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.2.22
      ansible.builtin.import_tasks:
        file: error_logging.yml
