---
- name: 5.2.9
  tags:
    - 5.2.9
    - level_1_server
    - level_1_workstation
  when:
    # section_5_2_9
    - sshd_disable_host_based_auth | bool
  block:
    - name: |
        ---
        5.2.9 Ensure SSH HostbasedAuthentication is disabled
        > Edit /etc/ssh/sshd_config
        ---
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^HostbasedAuthentication\s+(?:(?!\bno\b).)*'
        line: "HostbasedAuthentication no"
        create: true
        owner: root
        group: root
        mode: "0600"
      notify: "reload sshd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.2.9
      ansible.builtin.import_tasks:
        file: error_logging.yml
