---
- name: 5.2.23
  tags:
    - 5.2.23
    - level_1_server
    - level_1_workstation
  when:
    # section_5_2_23
    - sshd_max_startups_conf | bool
  block:
    - name: |
        ---
        5.2.23 Ensure SSH MaxSessions is set to 4 or less
        > Edit /etc/ssh/sshd_config
        ---
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxSessions\s+(?:(?!\b{{ sshd_max_sessions }}\b).)*'
        line: "MaxSessions {{ sshd_max_sessions }}"
        create: true
        owner: root
        group: root
        mode: "0600"
      notify: "reload sshd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.2.23
      ansible.builtin.import_tasks:
        file: error_logging.yml
