---
- name: 5.2.11
  tags:
    - 5.2.11
    - level_1_server
    - level_1_workstation
  when:
    # section_5_2_11
    - sshd_disable_empty_passwords | bool
  block:
    - name: |
        ---
        5.2.11 Ensure SSH PermitEmptyPasswords is disabled
        > Edit /etc/ssh/sshd_config
        ---
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitEmptyPasswords\s+(?:(?!\bno\b).)*'
        line: "PermitEmptyPasswords no"
        create: true
        owner: root
        group: root
        mode: "0600"
      notify: "reload sshd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.2.11
      ansible.builtin.import_tasks:
        file: error_logging.yml
