---
- name: 5.2.7
  tags:
    - 5.2.7
    - level_1_server
    - level_1_workstation
  when:
    # section_5_2_7
    - sshd_max_auth_tries_conf | bool
  block:
    - name: |
        ---
        5.2.7 Ensure SSH MaxAuthTries is set to 4 or less
        > Edit /etc/ssh/sshd_config
        ---
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxAuthTries\s+(?:(?!\b{{ ssh_max_auth_tries }}\b)\d)*'
        line: "MaxAuthTries {{ ssh_max_auth_tries }}"
        create: true
        owner: root
        group: root
        mode: "0600"
      notify: "reload sshd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.2.7
      ansible.builtin.import_tasks:
        file: error_logging.yml
