---
- name: 5.2.8
  tags:
    - 5.2.8
    - level_1_server
    - level_1_workstation
  when:
    # section_5_2_8
    - sshd_ignore_rhosts | bool
  block:
    - name: |
        ---
        5.2.8 Ensure SSH IgnoreRhosts is enabled
        > Edit /etc/ssh/sshd_config
        ---
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^IgnoreRhosts\s+(?:(?!\byes\b).)*'
        line: "IgnoreRhosts yes"
        create: true
        owner: root
        group: root
        mode: "0600"
      notify: "reload sshd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.2.8
      ansible.builtin.import_tasks:
        file: error_logging.yml
