---
- name: 5.2.12
  tags:
    - 5.2.12
    - level_1_server
    - level_1_workstation
  when:
    # section_5_2_12
    - sshd_disable_environment_vars | bool
  block:
    - name: |
        ---
        5.2.12 Ensure SSH PermitUserEnvironment is disabled
        > Edit /etc/ssh/sshd_config
        ---
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitUserEnvironment\s+(?:(?!\bno\b).)*'
        line: "PermitUserEnvironment no"
        create: true
        owner: root
        group: root
        mode: "0600"
      notify: "reload sshd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.2.12
      ansible.builtin.import_tasks:
        file: error_logging.yml
