---
- name: 5.3.1 Ensure password creation requirements are configured
  ansible.builtin.import_tasks:
    file: ./5.3.1.yml

- name: 5.3.2 Ensure lockout for failed password attempts is configured
  ansible.builtin.import_tasks:
    file: ./5.3.2.yml

- name: 5.3.3 Ensure password reuse is limited
  ansible.builtin.import_tasks:
    file: ./5.3.3.yml

- name: 5.3.4 Ensure password hashing algorithm is SHA-512
  ansible.builtin.import_tasks:
    file: ./5.3.4.yml
