---
- name: Filesystem configuration
  become: true
  gather_facts: true
  hosts:
    - alma
  roles:
    - role: cis_independent_linux
      vars:
        default_all_sections: false
        section_1_1_21: true
