---
- name: Filesystem configuration
  become: true
  gather_facts: true
  hosts:
    - alma
  roles:
    - role: filesystem
      vars:
        default_bool: false
        section_1_1_16: true
        default_all_sections: false
