---
- name: Filesystem configuration
  become: true
  gather_facts: true
  hosts:
    - alma
    - opensuse
    - ubuntu
  roles:
    - role: cis_independent_linux
      vars:
        default_all_sections: true
