---
- name: Filesystem configuration
  become: true
  gather_facts: true
  hosts:
    - testing
    # - alma
    # - opensuse
    # - ubuntu
  roles:
    - role: cis_independent_linux
      vars:
        default_all_sections: true
        mandatory_access_control:
          Suse: selinux
        disable_inetd_services:
          daytime: false
