---
- name: 5.4.5
  tags:
    - 5.4.5
    - level_1_server
    - level_1_workstation
  when:
    # section_5_4_5
    - default_user_shell_timeout_conf | bool
  vars:
    conf_files:
      - /etc/profile
  block:
    - name: |
        ---
        5.4.5 Ensure default user shell timeout is 900 seconds or less
        > Get files with TMOUT configuration
        ---
      ansible.builtin.shell: >-
        grep -lP '^TMOUT=' /etc/*shrc /etc/profile.d/*
      register: tmout_conf_files
      changed_when: false
      failed_when: tmout_conf_files.rc > 2

    - name: |
        ---
        5.4.5 Ensure default user shell timeout is 900 seconds or less
        > Set TMOUT={{ user_shell_timeout }}
        ---
      ansible.builtin.lineinfile:
        path: "{{ file }}"
        regexp: '^TMOUT=(?:(?!\b{{ user_shell_timeout }}\b).)*'
        line: "TMOUT={{ user_shell_timeout }}"
      loop: "{{ conf_files | union(tmout_conf_files.stdout_lines) | unique }}"
      loop_control:
        loop_var: file
        label: "{{ file }}"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.4.5
      ansible.builtin.import_tasks:
        file: error_logging.yml
