---
- name: 5.4.5
  tags:
    - 5.4.5
    - level_1_server
    - level_1_workstation
  when:
    # section_5_4_5
    - default_user_shell_timeout_conf | bool
  vars:
    conf_files:
      - /etc/profile
  block:
    - name: |
        ---
        5.4.5 Ensure default user shell timeout is 900 seconds or less
        > Get files with TMOUT configuration
        ---
      ansible.builtin.shell: >-
        grep -lP '^(declare -xr\s+)?TMOUT=' /etc/*shrc /etc/profile.d/*
      register: tmout_confs
      changed_when: false
      failed_when: tmout_confs.rc > 2

    - name: Non RedHat
      when:
        - ansible_os_family != "RedHat"
      block:
        - name: |
            ---
            5.4.5 Ensure default user shell timeout is 900 seconds or less
            > Set TMOUT={{ user_shell_timeout }} (Non RedHat)
            ---
          ansible.builtin.lineinfile:
            path: "{{ file }}"
            regexp: '^TMOUT=(?:(?!\b{{ user_shell_timeout }}\b).)*'
            line: "TMOUT={{ user_shell_timeout }}"
          loop: "{{ conf_files | union(tmout_confs.stdout_lines) | unique }}"
          loop_control:
            loop_var: file
            label: "{{ file }}"

        - name: |
            ---
            5.4.5 Ensure default user shell timeout is 900 seconds or less
            > Set TMOUT as readonly (Non RedHat)
            ---
          ansible.builtin.lineinfile:
            path: "{{ file }}"
            regexp: '^readonly\s+TMOUT$'
            line: "readonly TMOUT"
            insertafter: "^TMOUT="
          loop: "{{ conf_files | union(tmout_confs.stdout_lines) | unique }}"
          loop_control:
            loop_var: file
            label: "{{ file }}"

        - name: |
            ---
            5.4.5 Ensure default user shell timeout is 900 seconds or less
            > Export TMOUT (Non RedHat)
            ---
          ansible.builtin.lineinfile:
            path: "{{ file }}"
            regexp: '^export\s+TMOUT$'
            line: "export TMOUT"
            insertafter: "^readonly TMOUT$"
          loop: "{{ conf_files | union(tmout_confs.stdout_lines) | unique }}"
          loop_control:
            loop_var: file
            label: "{{ file }}"

    - name: RedHat
      when:
        - ansible_os_family == "RedHat"
      block:
        - name: |
            ---
            5.4.5 Ensure default user shell timeout is 900 seconds or less
            > Export TMOUT as readonly (RedHat)
            ---
          vars:
            tmout: "{{ user_shell_timeout }}"
          ansible.builtin.lineinfile:
            path: "{{ file }}"
            regexp: '^(declare -xr\s+)?TMOUT=(?:(?!\b{{ tmout }}\b).)*'
            line: "declare -xr TMOUT={{ tmout }}"
          loop: "{{ conf_files | union(tmout_confs.stdout_lines) | unique }}"
          loop_control:
            loop_var: file
            label: "{{ file }}"


  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.4.5
      ansible.builtin.import_tasks:
        file: error_logging.yml
