---
- name: 5.6
  tags:
    - 5.6.x
    - level_1_server
    - level_1_workstation
  when:
    # section_5_6
    - restrict_su_command | bool
  block:
    - name: |
        ---
        5.6 Ensure access to the su command is restricted
        > Edit /etc/pam.d/su
        ---
      ansible.builtin.lineinfile:
        path: /etc/pam.d/su
        regexp: '^auth\s+.+pam_wheel\.so(?:(?!\buse_suid\b).)*'
        line: "auth required pam_wheel.so use_uid"
        insertbefore: '^[#\s]*auth\s+'
        create: true
        owner: root
        group: root
        mode: "0644"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.6
      ansible.builtin.import_tasks:
        file: error_logging.yml
