---
- name: 5.1 Configure Cron
  tags:
    - 5.1.x
  ansible.builtin.import_tasks:
    file: ./5.1/main.yml

- name: 5.2 SSH Server Configuration
  tags:
    - 5.2.x
  ansible.builtin.import_tasks:
    file: ./5.2/main.yml

- name: 5.3 Configure PAM
  tags:
    - 5.3.x
  ansible.builtin.import_tasks:
    file: ./5.3/main.yml

- name: 5.4 User Accounts and Environment
  tags:
    - 5.4.x
  ansible.builtin.import_tasks:
    file: ./5.4/main.yml

- name: 5.5 Ensure root login is restricted to system console
  tags:
    - 5.5.x
  ansible.builtin.import_tasks:
    file: ./5.5.yml

- name: 5.6 Ensure access to the su command is restricted
  tags:
    - 5.6.x
  ansible.builtin.import_tasks:
    file: ./5.6.yml
