---
- name: 4.1.1.3 Ensure audit logs are not automatically deleted
  tags:
    - 4.1.1.3
    - level_2_server
    - level_2_workstation
  when:
    # section_4_1_1_3
    - rotate_logs | bool
    - not is_container
  block:
    - name: |
        ---
        4.1.1.3 Ensure audit logs are not automatically deleted
        > Edit /etc/audit/auditd.conf
        ---
      vars:
        confs:
          - key: max_log_file_action
            value: keep_logs
      ansible.builtin.lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^{{ conf.key }}\s*=\s*(?:(?!{{ conf.value }}).)*'
        line: "{{ conf.key }} = {{ conf.value }}"
        state: present
        backup: true
      loop: "{{ confs }}"
      loop_control:
        loop_var: conf
        label: "{{ conf.key }} = {{ conf.value }}"
      notify: "reload auditd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 4.1.1.3
      ansible.builtin.import_tasks:
        file: error_logging.yml
