---
- name: 4.1.1.1 Ensure audit log storage size is configured
  tags:
    - 4.1.1.1
    - level_2_server
    - level_2_workstation
  when:
    # section_4_1_1_1
    - conf_audit_log_storage_size | bool
    - not is_container
  block:
    - name: |
        ---
        4.1.1.1 Ensure audit log storage size is configured
        > Edit /etc/audit/auditd.conf (max_log_file = {{ max_log_file }})
        ---
      ansible.builtin.lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^max_log_file\s*=\s*(?:(?!\b{{ max_log_file }}\b).)*'
        line: "max_log_file = {{ max_log_file }}"
        state: present
        backup: true
      notify: "reload auditd"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 4.1.1.1
      ansible.builtin.import_tasks:
        file: error_logging.yml
