---
- name: 4.1.1.1 Ensure audit log storage size is configured
  ansible.builtin.import_tasks:
    file: ./4.1.1.1.yml

- name: 4.1.1.2 Ensure system is disabled when audit logs are full
  ansible.builtin.import_tasks:
    file: ./4.1.1.2.yml

- name: 4.1.1.3 Ensure audit logs are not automatically deleted
  ansible.builtin.import_tasks:
    file: ./4.1.1.3.yml
