---
- name: 3.7
  tags:
    - level_2_server
    - level_2_workstation
  when:
    # section_3_7
    - disable_ipv6 | bool
    - not is_container
    - grub_v2
  block:
    - name: |
        ---
        3.7 Disable IPv6
        > Get GRUB_CMDLINE_LINUX value from /etc/default/grub
        ---
      ansible.builtin.shell: >
        grep -oP '(?<=^GRUB_CMDLINE_LINUX=").*(?="$)' /etc/default/grub
      register: raw_args
      changed_when: false
      failed_when: false

    - name: |
        ---
        3.7 Disable IPv6
        > Add boot parameter 'ipv6.disable=1'
        ---
      when:
        - "'ipv6.disable=1' not in raw_args.stdout"
      vars:
        new_args: >-
          {{ (raw_args.stdout.split() + ['ipv6.disable=1']) | join(' ') }}
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX=".*"'
        line: 'GRUB_CMDLINE_LINUX="{{ new_args }}"'
        backup: true
      notify: "grub mkconfig"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 3.7
      ansible.builtin.import_tasks:
        file: error_logging.yml
