---
- name: Flush IPv6 ip6tables
  when:
    - flush_ip6tables | bool
    - 'ansible_os_family != "Suse"'
  block:
    - name: Flush IPv6 ip6tables
      ansible.builtin.iptables:
        flush: true
        ip_version: ipv6

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: "3.5.1-flush"
      ansible.builtin.import_tasks:
        file: error_logging.yml
