---
- name: Flush IPv6 ip6tables
  ansible.builtin.import_tasks:
    file: ./flush-ip6tables.yml

- name: 3.5.1.2 Ensure IPv6 loopback traffic is configured
  ansible.builtin.import_tasks:
    file: ./3.5.1.2.yml

- name: 3.5.1.3 Ensure IPv6 outbound and established connections are configured
  ansible.builtin.import_tasks:
    file: ./3.5.1.3.yml

- name: 3.5.1.4 Ensure IPv6 firewall rules exists for all open ports
  ansible.builtin.import_tasks:
    file: ./3.5.1.4.yml

- name: 3.5.1.1 Ensure IPv6 default deny firewall policy
  ansible.builtin.import_tasks:
    file: ./3.5.1.1.yml

- name: Save ip6tables rules
  ansible.builtin.import_tasks:
    file: ./save-ip6tables-rules.yml
