---
- name: Bootstrap
  ansible.builtin.import_tasks:
    file: bootstrap.yml

- name: "1 Initial Setup"
  tags:
    - 1.x
  ansible.builtin.import_tasks:
    file: ./1-initial-setup/main.yml

- name: "2 Services"
  tags:
    - 2.x
  ansible.builtin.import_tasks:
    file: ./2-services/main.yml

- name: "3 Network Configuration"
  tags:
    - 3.x
  ansible.builtin.import_tasks:
    file: ./3-network-configuration/main.yml

- name: "4 Logging and Auditing"
  tags:
    - 4.x
  ansible.builtin.import_tasks:
    file: ./4-logging-and-auditing/main.yml

- name: "5 Access, Authentication and Authorization"
  tags:
    - 5.x
  ansible.builtin.import_tasks:
    file: ./5-aaa/main.yml

- name: "6 System Maintenance"
  tags:
    - 6.x
  ansible.builtin.import_tasks:
    file: ./6-system-maintenance/main.yml

- name: Flushing all handlers
  tags:
    - always
  ansible.builtin.meta: flush_handlers

- name: Info logging summary
  tags:
    - always
  ansible.builtin.debug:
    msg:
      - "Count: {{ info_count }}"
      - "Affected: {{ info_list }}"

- name: Caught errors summary
  tags:
    - always
  ansible.builtin.debug:
    msg:
      - "Count: {{ error_count }}"
      - "Affected: {{ error_list }}"

- name: Reboot
  tags:
    - always
  when:
    - reboot | default(false)
    - not is_container
  ansible.builtin.reboot:
    reboot_timeout: 600
