---
- name: Bootstrap
  ansible.builtin.import_tasks:
    file: bootstrap.yml

- name: "1 Initial Setup"
  tags:
    - 1.x
  ansible.builtin.import_tasks:
    file: ./1-initial-setup/main.yml

- name: Flushing all handlers
  tags:
    - always
  ansible.builtin.meta: flush_handlers

- name: Info logging summary
  tags:
    - always
  ansible.builtin.debug:
    msg: |
      Count: {{ info_count }}
      Affected: {{ info_list }}

- name: Caught errors summary
  tags:
    - always
  ansible.builtin.debug:
    msg: |
      Count: {{ error_count }}
      Affected: {{ error_list }}

- name: Reboot
  tags:
    - always
  when:
    - reboot | default(false)
    - not (is_container | default(false))
  ansible.builtin.reboot:
    reboot_timeout: 600
