---
- name: 5.1.2
  tags:
    - 5.1.2
    - level_1_server
    - level_1_workstation
  when:
    # section_5_1_2
    - crontab_permissions
  block:
    - name: |
        ---
        5.1.2 Ensure permissions on /etc/crontab are configured
        > Permission root:root 0600
        ---
      ansible.builtin.file:
        path: /etc/crontab
        owner: root
        group: root
        mode: "0600"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.1.2
      ansible.builtin.import_tasks:
        file: error_logging.yml
