---
- name: 5.1.4
  tags:
    - 5.1.4
    - level_1_server
    - level_1_workstation
  when:
    # section_5_1_4
    - cron_daily_permissions
  block:
    - name: |
        ---
        5.1.4 Ensure permissions on /etc/cron.daily are configured
        > Permission root:root 0700
        ---
      ansible.builtin.file:
        path: /etc/cron.daily
        owner: root
        group: root
        mode: "0700"

  rescue:
    - name: Flushing all handlers
      ansible.builtin.meta: flush_handlers

    - name: Error backtrace
      vars:
        section_id: 5.1.4
      ansible.builtin.import_tasks:
        file: error_logging.yml
