---
- name: 5.1.1 Ensure cron daemon is enabled
  ansible.builtin.import_tasks:
    file: ./5.1.1.yml

- name: 5.1.2 Ensure permissions on /etc/crontab are configured
  ansible.builtin.import_tasks:
    file: ./5.1.2.yml

- name: 5.1.3 Ensure permissions on /etc/cron.hourly are configured
  ansible.builtin.import_tasks:
    file: ./5.1.3.yml

- name: 5.1.4 Ensure permissions on /etc/cron.daily are configured
  ansible.builtin.import_tasks:
    file: ./5.1.4.yml

- name: 5.1.5 Ensure permissions on /etc/cron.weekly are configured
  ansible.builtin.import_tasks:
    file: ./5.1.5.yml

- name: 5.1.6 Ensure permissions on /etc/cron.monthly are configured
  ansible.builtin.import_tasks:
    file: ./5.1.6.yml

- name: 5.1.7 Ensure permissions on /etc/cron.monthly are configured
  ansible.builtin.import_tasks:
    file: ./5.1.7.yml

- name: 5.1.8 Ensure at/cron is restricted to authorized users
  ansible.builtin.import_tasks:
    file: ./5.1.8.yml
