---
- name: Tasks to chpasswd
  tags:
    - chpasswd
  when:
    - chpasswd | bool
  block:
    - name: Check if new password is provided
      vars:
        _host: "{{ hostvars[host] }}"
        _new_passwd: "{{ _host['new_passwd'] | default(new_passwd) }}"
        curr_passwd: "{{ _host['ansible_password'] }}"
      ansible.builtin.fail:
        msg: "Please provide a new password"
      loop: "{{ groups['all'] }}"
      loop_control:
        loop_var: host
      failed_when:
        - not _new_passwd

    - name: Change password if expired on initial login
      vars:
        _host: "{{ hostvars[host] }}"
        curr_passwd: "{{ _host['ansible_password'] }}"
        _new_passwd: "{{ _host['new_passwd'] | default(new_passwd) }}"
        hostname: "{{ _host['inventory_hostname'] }}"
        username: "{{ _host['ansible_user'] }}"
        ip_addr: "{{ _host['ansible_host'] }}"
        conn: "{{ username }}@{{ ip_addr }}"
      ansible.builtin.expect:
        command: >-
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          {{ conn }}
        timeout: 10
        responses:
          '(?i)password:': "{{ curr_passwd }}"
          'Current password:': "{{ curr_passwd }}"
          'UNIX password:': "{{ curr_passwd }}"
          '(?i)new password:': "{{ _new_passwd }}"
      register: login_check
      loop: "{{ groups['all'] }}"
      loop_control:
        loop_var: host
        label: "{{ hostname }}: {{ conn }}"
      changed_when:
        - '"Changing password" in login_check.stdout'
        - login_check.rc == 0

    - name: Check if password has been changed
      vars:
        message: >-
          {%- if chk.changed -%}
            Password has been changed, please update your inventory accordingly
          {%- else -%}
            No password change as it is not expired
          {%- endif -%}
      ansible.builtin.debug:
        msg: "{{ message }}"
      changed_when: chk.changed
      loop: "{{ login_check.results }}"
      loop_control:
        loop_var: chk
        label: "{{ chk['host'] }}"
